### PR TITLE
Rename .nearestPowerOfTwo to .floorPowerOfTwo

### PR DESCRIPTION
**Pull request by alizenguyen**
Hello, I was receiving a warning with THREE.Math where a function was renamed (see image). The warning became especially excessive when a fps was set. I renamed name the function accordingly.

Screen Shot 2020-01-23 at 1 29 45 PM

### CODE REVIEW

**Review by riccardogiorato — CHANGES_REQUESTED** [review]
Hey @alizenguyen can you also bump the version of the package to a minor upgraded version? This will enable fast merge into master to be published on NPM.

Current latest version on NPM is 0.2.0 you could set it to: 0.2.1

**Comment by alizenguyen** [comment]
@Giorat Done! Let me know if there's anything else.

**Comment by riccardogiorato** [comment]
Why did you close this Pull Request?

**Comment by alizenguyen** [comment]
I’ll reopen it later today. I was curious and testing something. 😂

**Pull request closed without merging**
